{{- if .Values.podMonitor.create -}}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "k8s-node-latency.fullname" . }}
  labels:
    {{- include "k8s-node-latency.labels" . | nindent 4 }}
spec:
  podMetricsEndpoints:
    - honorLabels: true
      interval: 15s
      path: /metrics
      targetPort: 2112
      scheme: http
  selector:
    matchLabels:
      {{- include "k8s-node-latency.selectorLabels" . | nindent 6 }}
{{- end }}